@HOST =  http://localhost:3000

GET {{HOST}}/api/students

###
POST {{HOST}}/api/students
Content-Type: application/json

{
    "name": "Juam",
    "surname": "Tjnk",
    "phone": "738247824",
    "email": "juanghn@alumnostrazos.net"
}

###
PUT  {{HOST}}/api/students/686f7fc0a2085c05d6e7a24d
Content-Type: application/json

{
    "surname": "Taraschi"
}

###
DELETE   {{HOST}}/api/students/686f7fc0a2085c05d6e7a24d
Content-Type: application/json

##########
#TEACHERS#
##########

GET {{HOST}}/api/teachers

###
POST {{HOST}}/api/teachers
Content-Type: application/json

{
    "name": "Pepe",
    "surname": "Perex",
    "age": 18,
    "available": true
}

