@HOST =  http://localhost:3000

GET {{HOST}}/api/students

###
POST {{HOST}}/api/students
Content-Type: application/json

{
    "name": "Sabrina",
    "surname": "Taraschi",
    "phone": "738247824",
    "email": "sabrinataraschi@alumnostrazos.net"
}

##########
#TEACHERS#
##########

GET {{HOST}}/api/teachers

###
POST {{HOST}}/api/teachers
Content-Type: application/json

{
    "name": "Pepe",
    "surname": "Perex",
    "age": 18,
    "available": true
}